<a href="https://colab.research.google.com/github/bharathulaprasad/cs360ml/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Part 1 - Python Basics 

#1
#Write a command to get the Python version you are using.
!python --version

Python 3.6.9


In [ ]:
#2
# Write a command or program to locate Python site-packages
import site; 
print(site.getsitepackages())

['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']


In [ ]:
#3
# Write a command or program to get the path and name of the file that is currently executing.
from pathlib import Path
import os

print('File dir:', os.path.dirname(''))
print('File name:', Path(os.path.abspath('')).resolve().stem)


File dir: 
File name: content


In [ ]:
#4
# Write a python program to randomly generate two matrices of
# size [2x3 and 3x2] and do the matrix multiplication using
# the two generated matrices. (Say A = BC)
import numpy as np
B= np.random.rand(2,3)
C=np.random.rand(3,2)
A=np.matmul(B,C)
A

array([[0.6664182 , 0.28733952],
       [0.3175027 , 0.1406193 ]])

In [ ]:
#5
#  Use a for loop to implement the above question five times
# and thereafter take the average of all the five matrices
# and display the result.
import numpy as np
#create for loop for 5 times
i = 0
while i < 5:
  B = np.random.rand(2,2)
  A = np.add(A,B)
  i += 1
np.divide(A,5)
print (A)


[[3.89865988 3.6212107 ]
 [3.87715932 3.3753419 ]]


In [ ]:
#6
# Write a program to transfer the matrix (generated in
#question 5) to the CSV file and then read the same matrix
#and display the transposition of it.
from numpy import genfromtxt
np.savetxt("foo.csv", A, delimiter=",")
print(genfromtxt('foo.csv', delimiter=','))
print(A.transpose())

[[21.70425081 18.32056069]
 [20.12660461 22.8338985 ]]
[[21.70425081 20.12660461]
 [18.32056069 22.8338985 ]]


In [ ]:
#7 
# Write a program to find the mean, mode, and median of the
#above-mentioned matrix.
from scipy import stats
A = np.array([[30,80,10],[80,80,10],[80,50,50]]) 
print(np.mean(A))
print(np.median(A))
print(stats.mode(A))

52.22222222222222
50.0
ModeResult(mode=array([[80, 80, 10]]), count=array([[2, 2, 2]]))


In [ ]:
# 8 
# upper traingle of the above array
print(A[np.triu_indices(3)])

[30 80 10 80 10 50]


In [ ]:
# 9
# Write a Python program to read specific columns of a given
#CSV file and print the content of the columns
# (Column number should be given by the user)
import pandas as pd
column=input("input column number to read in csv like 0, 1, 2, or 3 : ")
name = ["aparna", "pankaj", "krishna", "sudhir"] 
degree = ["MBA", "BCA", "M.Tech", "MBA"] 
score = [90, 40, 80, 98] 
dict = {'name': name, 'degree': degree, 'score': score}       
df = pd.DataFrame(dict) 
df.to_csv('scores.csv') 
# saving the dataframe  
df = pd.read_csv('scores.csv',usecols=[int(column)], low_memory = True)
print(df)

input column number to read in csv like 0, 1, 2, or 3 : 3
   score
0     90
1     40
2     80
3     98


In [ ]:
# 10
# Write a Python program to replace a user-defined number
# present in the CSV file by the character ‘A’
import pandas as pd 

# Making data frame from the csv file 
df = pd.read_csv("scores.csv") 
# Printing the first 4 rows of the data frame for visualization 
print("before changing\n", ) 
print(df[:4])
column=input("value to replace: ");
df.replace(to_replace =int(column), 
                 value ='A', inplace=True) 

print("changing now")
df.to_csv("scores_changed.csv")
df = pd.read_csv("scores_changed.csv") 
print(df[:4])

before changing

   Unnamed: 0     name  degree  score
0           0   aparna     MBA     90
1           1   pankaj     BCA     40
2           2  krishna  M.Tech     80
3           3   sudhir     MBA     98
value to replace: 40
changing now
   Unnamed: 0  Unnamed: 0.1     name  degree score
0           0             0   aparna     MBA    90
1           1             1   pankaj     BCA     A
2           2             2  krishna  M.Tech    80
3           3             3   sudhir     MBA    98


In [ ]:
# Part 2 Numpy Basics
#1
# Write a NumPy program to create an array of 10 zeros,10 ones,
# 10 fives
import numpy as np
array=np.zeros(10)*0
print("An array of 10 zeros:")
print(array)
array=np.ones(10)*1
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#2
#Write a NumPy program to create an array of all the even
#integers from 10 to 50
import numpy as np
array=np.arange(10,50,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#3
#Write a NumPy program to generate a random number between 0 and 1
import random as rand
rand.uniform(0,1)


0.5710369535276596

In [ ]:
#4
# Write a NumPy program to save the matrix
import numpy as np
A=np.random.rand(2,2)
print ("actual random array is :\n" + str(A))
np.savetxt("array_save.txt",A, fmt='%f')
print("reading from file :\n"+ str(np.loadtxt("array_save.txt", dtype=float)))

actual random array is :
[[0.62396438 0.72866914]
 [0.321786   0.38656058]]
reading from file :
[[0.623964 0.728669]
 [0.321786 0.386561]]


In [ ]:
# Part 3
# 1
# Write a python program to read an image and save the image as a
# matrix to a .csv file using pandas
from PIL import Image
from numpy import matrix
import numpy as np

image = Image.open("sample_data/Home.jpg")
image.load()
imagearray = np.asarray(image)
# print first two elemnts as test
print(imagearray[:2])
np.save("sample_data/imagedata.csv",imagearray)



[[[152 170 208]
  [141 159 197]
  [142 161 201]
  ...
  [153 180 235]
  [154 181 236]
  [155 182 237]]

 [[181 197 230]
  [164 183 216]
  [155 174 207]
  ...
  [151 181 235]
  [152 182 236]
  [152 182 236]]]


In [ ]:
# 2
#Write a program to import excel data from the .csv file
#(generated in question 1) by excluding the last row and last column
import pandas as pd
read_file=pd.read_csv("sample_data/california_housing_test.csv")
# remove the last column
read_file.drop(read_file.columns[-1], axis=1, inplace=True)
# remove last row
read_file = read_file[:-1]
read_file.to_excel ('sample_data/sample.xlsx')


In [ ]:
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-01-10 00:00:00


In [ ]:
# Part 4
# Create a mini calculator to know the age of a person after
# putting the range (i.e. date of birth and current date)
birth = input("Input your birth year :" )
birth = int(birth)
today = date.today() 
age = today.year - birth
print(age)

Input your birth year :1981
40
