<a href="https://colab.research.google.com/github/bharathulaprasad/cs360ml/blob/main/Assignment_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1:Implement the single layer perceptron (SLP) for the OR and
AND problem. Please make sure the followings: Marks: 10

a. Activation function is threshold activation.

b. Train the model for different learning rates (LR),
where 0<LR<1. 
Train for 5 different learning rates and
plot the training curve(epoch vs training accuracy).

c. Weight initialization should be between -0.3 to 0.3

In [143]:
# Problem 1:
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial
from collections import Counter

from sklearn.metrics import accuracy_score

In [144]:
# Define input features(OR GATE) and (AND GATE) respectively
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
input_features1 = np.array([[0,0],[0,1],[1,0],[1,1]])


# Define target output:
target_output = np.array([[0,1,1,1]])
target_output1 = np.array([[0,0,0,1]])

In [145]:
# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
print (target_output)

target_output1 = target_output1.reshape(4,1)
print(target_output1.shape)
print (target_output1)

(4, 1)
[[0]
 [1]
 [1]
 [1]]
(4, 1)
[[0]
 [0]
 [0]
 [1]]


In [146]:
# Define weights:
weights = np.array([[-0.3],[0.3]])
print(weights.shape)
print (weights)
# Bias weight:
bias = 0.3
# Learning Rate:
lr = 0.85

(2, 1)
[[-0.3]
 [ 0.3]]


In [147]:
# Activation function:
def sigmoid(x):
  return 1/(1+np.exp(-x))
# Derivative of activation function:
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))

In [148]:
# Running our code 10000 times:
for epoch in range(10000):
  inputs = input_features
  inputs = input_features1
#Feedforward input:
in_o = np.dot(inputs, weights) + bias 
#Feedforward output:
out_o = sigmoid(in_o) 
#Backpropagation
#Calculating error
error = out_o - target_output
error = out_o - target_output1

#Going with the formula:
x = error.sum()
print(x)

1.2945413398491135


In [149]:
#Calculating derivative:
derror_douto = error
douto_dino = sigmoid_der(out_o)
#Multiplying individual derivatives:
deriv = derror_douto * douto_dino 
#Multiplying with the 3rd individual derivative:
#Finding the transpose of input_features:
inputs = input_features.T
inputs = input_features1.T
deriv_final = np.dot(inputs,deriv)

In [150]:
#Updating the weights values:
weights -= lr * deriv_final 
#Updating the bias weight value:
for i in deriv:
 bias -= lr * i 
#Check the final values for weight and biasprint (weights)
print(weights)
print (bias) 

[[-0.31651391]
 [ 0.25952179]]
[0.04711738]


In [151]:
#Predictions 
#Taking inputs:
single_point = np.array([1,0])
 #1st step:
result1 = np.dot(single_point, weights) + bias 
#2nd step:
result2 = sigmoid(result1) 
#Print final result
print(result2) 
#2:
single_point = np.array([1,1]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2) 
#3.
single_point = np.array([0,0]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2)
#4.
single_point = np.array([0,1]) 
result1 = np.dot(single_point, weights) + bias 
result2 = sigmoid(result1) 
print(result2)

[0.43305525]
[0.49753134]
[0.51177717]
[0.57606471]


Problem 2: KNN Classifier

Implement the KNN classifier over the IRIS dataset


In [152]:
# Problem 2:
from sklearn import datasets
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
 
 
dataset = r'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' # use your path
iris = pd.read_csv(dataset, index_col=None, header=0)
 
iris.columns=['sepal length in cm', 'sepal width in cm', 'petal length in cm', 'petal width in cm', 'class']
iris_floats = iris[['sepal length in cm', 'sepal width in cm', 'petal length in cm', 'petal width in cm']].iloc[: , :].values

In [153]:
print(iris.shape)

(149, 5)


In [154]:

print(iris.head(20))

    sepal length in cm  sepal width in cm  ...  petal width in cm        class
0                  4.9                3.0  ...                0.2  Iris-setosa
1                  4.7                3.2  ...                0.2  Iris-setosa
2                  4.6                3.1  ...                0.2  Iris-setosa
3                  5.0                3.6  ...                0.2  Iris-setosa
4                  5.4                3.9  ...                0.4  Iris-setosa
5                  4.6                3.4  ...                0.3  Iris-setosa
6                  5.0                3.4  ...                0.2  Iris-setosa
7                  4.4                2.9  ...                0.2  Iris-setosa
8                  4.9                3.1  ...                0.1  Iris-setosa
9                  5.4                3.7  ...                0.2  Iris-setosa
10                 4.8                3.4  ...                0.2  Iris-setosa
11                 4.8                3.0  ...      

In [155]:
print(iris.groupby('class').size())

class
Iris-setosa        49
Iris-versicolor    50
Iris-virginica     50
dtype: int64


In [156]:
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
array = iris.values
X = array[:,0:4]
Y = array[:,4]
test_size = 0.20
seed = 7
X_train, X_validation, y_train, y_validation = model_selection.train_test_split(X, Y, test_size=test_size, random_state=seed)

seed = 7
scoring = 'accuracy'

In [162]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(KNeighborsClassifier(), X_train, y_train, cv=kfold, scoring=scoring)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
predictions = knn.predict(X_validation)
print(accuracy_score(y_validation, predictions))
print(confusion_matrix(y_validation, predictions))
print(classification_report(y_validation, predictions))

print("%.2f  %.4f " % (cv_results.mean(), cv_results.std()))

0.9333333333333333
[[ 7  0  0]
 [ 0 11  1]
 [ 0  1 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.92      0.92      0.92        12
 Iris-virginica       0.91      0.91      0.91        11

       accuracy                           0.93        30
      macro avg       0.94      0.94      0.94        30
   weighted avg       0.93      0.93      0.93        30

0.97  0.0534 


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Now trying the same without using in built functions.
Attempt 2:

In [158]:
# Now without using  built in functions
class KNN:
    def __init__(self, k):
        self.k = k
        
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        
    def distance(self, X1, X2):
        distance = scipy.spatial.distance.euclidean(X1, X2)
    
    def predict(self, X_test):
        final_output = []
        for i in range(len(X_test)):
            d = []
            votes = []
            for j in range(len(X_train)):
                dist = scipy.spatial.distance.euclidean(X_train[j] , X_test[i])
                d.append([dist, j])
            d.sort()
            d = d[0:self.k]
            for d, j in d:
                votes.append(y_train[j])
            ans = Counter(votes).most_common(1)[0][0]
            final_output.append(ans)
            
        return final_output
    
    def score(self, X_test, y_test):
        predictions = self.predict(X_test)
        return (predictions == y_test).sum() / len(y_test)


In [159]:
clf = KNN(3)
clf.fit(X_train, Y_train)
prediction = clf.predict(X_test)
print(prediction)
for i in prediction:
    print(i, end= ' ')

['Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica']
Iris-virginica Iris-versicolor Iris-setosa Iris-versicolor Iris-virginica Iris-setosa Iris-versicolor Iris-versicolor Iris-setosa Iris-versicolor Iris-versicolor Iris-versicolor Iris-setosa Iris-virginica Iris-setosa Iris-versicolor Iris-virginica Iris-virginica Iris-setosa Iris-setosa Iris-virginica Iris-virginica Iris-versicolor Iris-virginica Iris-virginica Iris-virginica Iris-versicolor Iris-versicolor Iris-virginica Iris-virginica 

In [160]:
prediction == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [161]:
clf.score(X_test, y_test)

0.9666666666666667

**So it is almost 0.93 to 0.96 accuracy score.**